---
- name: ensure packages for mysql are installed
  apt: name={{item}} state=present
  with_items:
      - mysql-server
      - mysql-client
      - php5-mysql
      - python2\.7-mysqldb


- name: ensure database is created
  sudo: yes
  mysql_db: name={{dbname}} state=present login_user=root login_password=""


- name: ensure user has access to database
  sudo: yes
  mysql_user: name={{dbuser}} password={{dbpassword}} priv={{dbname}}.*:ALL